/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Classes.Corretor;

/**
 * Tela de cadastro de corretor.
 * Essa tela faz as manipulações para salvar um novo corretor.
 * 
 * @author Gabriel Santos Pereira
 */
public class CadastroCorretor extends javax.swing.JFrame {

    static ArrayList<Corretor> listaCorretor;
    
    /**
     * Creates new form CadastroCorretor
     */
    public CadastroCorretor() {
        initComponents();
        
        listaCorretor = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosCorretor = new javax.swing.JPanel();
        lblNomeCorretor = new javax.swing.JLabel();
        lblRgCorretor = new javax.swing.JLabel();
        lblCpfCorretor = new javax.swing.JLabel();
        lblDataDeNascimentoCorretor = new javax.swing.JLabel();
        lblTelefoneCorretor = new javax.swing.JLabel();
        lblSalarioCorretor = new javax.swing.JLabel();
        lblSenhaCorretor = new javax.swing.JLabel();
        lblCreciCorretor = new javax.swing.JLabel();
        txtNomeCorretor = new javax.swing.JTextField();
        txtRgCorretor = new javax.swing.JTextField();
        txtCpfCorretor = new javax.swing.JTextField();
        txtDataDeNascimentoCorretor = new javax.swing.JTextField();
        txtTelefoneCorretor = new javax.swing.JTextField();
        txtSalarioCorretor = new javax.swing.JTextField();
        txtSenhaCorretor = new javax.swing.JTextField();
        txtCreciCorretor = new javax.swing.JTextField();
        btnSalvarCorretor = new javax.swing.JButton();
        btnLimparCorretor = new javax.swing.JButton();
        btnLimparCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeCorretor.setText("Nome Corretor:");

        lblRgCorretor.setText("RG Corretor:");

        lblCpfCorretor.setText("CPF Corretor:");

        lblDataDeNascimentoCorretor.setText("Data de Nascimento:");

        lblTelefoneCorretor.setText("Telefone:");

        lblSalarioCorretor.setText("Salário:");

        lblSenhaCorretor.setText("Senha:");

        lblCreciCorretor.setText("Creci Corretor: ");

        txtRgCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgCorretorActionPerformed(evt);
            }
        });

        txtTelefoneCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneCorretorActionPerformed(evt);
            }
        });

        txtCreciCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreciCorretorActionPerformed(evt);
            }
        });

        btnSalvarCorretor.setText("Salvar");
        btnSalvarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCorretorActionPerformed(evt);
            }
        });

        btnLimparCorretor.setText("Limpar");
        btnLimparCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCorretorActionPerformed(evt);
            }
        });

        btnLimparCancelar.setText("Cancelar");
        btnLimparCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosCorretorLayout = new javax.swing.GroupLayout(pnlDadosCorretor);
        pnlDadosCorretor.setLayout(pnlDadosCorretorLayout);
        pnlDadosCorretorLayout.setHorizontalGroup(
            pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addComponent(btnSalvarCorretor)
                        .addGap(135, 135, 135)
                        .addComponent(btnLimparCorretor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparCancelar)
                        .addGap(45, 45, 45))
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(txtNomeCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNomeCorretor)
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addComponent(lblRgCorretor)
                                .addGap(63, 63, 63)
                                .addComponent(txtRgCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addComponent(lblCpfCorretor)
                                .addGap(57, 57, 57)
                                .addComponent(txtCpfCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenhaCorretor)
                                    .addComponent(lblSalarioCorretor)
                                    .addComponent(lblTelefoneCorretor)
                                    .addComponent(lblCreciCorretor))
                                .addGap(48, 48, 48)
                                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSalarioCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefoneCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenhaCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCreciCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosCorretorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDataDeNascimentoCorretor)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataDeNascimentoCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))))
        );
        pnlDadosCorretorLayout.setVerticalGroup(
            pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCorretor)
                    .addComponent(txtNomeCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgCorretor)
                    .addComponent(txtRgCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCorretor)
                    .addComponent(txtCpfCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimentoCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataDeNascimentoCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaCorretor)
                    .addComponent(txtSenhaCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreciCorretor)
                    .addComponent(txtCreciCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarCorretor)
                    .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimparCorretor)
                        .addComponent(btnLimparCancelar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosCorretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosCorretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRgCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgCorretorActionPerformed

    private void txtTelefoneCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneCorretorActionPerformed

    private void btnLimparCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCancelarActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_btnLimparCancelarActionPerformed

    private void btnLimparCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCorretorActionPerformed
    // Limpar os campos
    //txtIdCorretor.setText("");
    txtNomeCorretor.setText("");
    txtRgCorretor.setText("");
    txtCpfCorretor.setText("");
    txtDataDeNascimentoCorretor.setText("");
    txtTelefoneCorretor.setText("");
    txtSalarioCorretor.setText("");
    txtSenhaCorretor.setText("");
    txtCreciCorretor.setText("");
    }//GEN-LAST:event_btnLimparCorretorActionPerformed

    private void btnSalvarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCorretorActionPerformed
    // Salvar um novo corretor
    // Faz a validação para saber se preencheu todos os campos
    /*if(txtIdCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    }*/
    if (txtNomeCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtRgCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtCpfCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtDataDeNascimentoCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtTelefoneCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtSalarioCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtSenhaCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtCreciCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else {
        //int idCorretor_ = Integer.parseInt(txtIdCliente.getText());
        String nomeCorretor_ = txtNomeCorretor.getText();
        String rgCorretor_ = txtRgCorretor.getText();
        String cpfCorretor_ = txtCpfCorretor.getText();
        String dataNascimentoCorretor_ = txtDataDeNascimentoCorretor.getText();
        String telefoneCorretor_ = txtTelefoneCorretor.getText();
        float salarioCorretor_ = Float.parseFloat(txtSalarioCorretor.getText());
        String senhaCorretor_ = txtSenhaCorretor.getText();
        String creciCorretor_ = txtCreciCorretor.getText();

        Corretor corretor = new Corretor(0, nomeCorretor_, rgCorretor_, cpfCorretor_, dataNascimentoCorretor_, telefoneCorretor_, "Corretor", salarioCorretor_, senhaCorretor_, false, creciCorretor_);

        JOptionPane.showMessageDialog(null, "Corretor cadastrado com Sucesso!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);

        listaCorretor.add(corretor);
        }
    }//GEN-LAST:event_btnSalvarCorretorActionPerformed

    private void txtCreciCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreciCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreciCorretorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnCancelarCliente1;
    private javax.swing.JButton btnCancelarCliente2;
    private javax.swing.JButton btnLimparCancelar;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnLimparCliente1;
    private javax.swing.JButton btnLimparCliente2;
    private javax.swing.JButton btnLimparCorretor;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JButton btnSalvarCliente1;
    private javax.swing.JButton btnSalvarCliente2;
    private javax.swing.JButton btnSalvarCorretor;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblCpfCliente1;
    private javax.swing.JLabel lblCpfCliente2;
    private javax.swing.JLabel lblCpfCorretor;
    private javax.swing.JLabel lblCreciCorretor;
    private javax.swing.JLabel lblDataDeNascimentoCliente;
    private javax.swing.JLabel lblDataDeNascimentoCliente1;
    private javax.swing.JLabel lblDataDeNascimentoCliente2;
    private javax.swing.JLabel lblDataDeNascimentoCorretor;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeCliente1;
    private javax.swing.JLabel lblNomeCliente2;
    private javax.swing.JLabel lblNomeCorretor;
    private javax.swing.JLabel lblOcupacaoCliente;
    private javax.swing.JLabel lblOcupacaoCliente1;
    private javax.swing.JLabel lblOcupacaoCliente2;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblRgCliente1;
    private javax.swing.JLabel lblRgCliente2;
    private javax.swing.JLabel lblRgCorretor;
    private javax.swing.JLabel lblSalarioCorretor;
    private javax.swing.JLabel lblSenhaCorretor;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JLabel lblTelefoneCliente1;
    private javax.swing.JLabel lblTelefoneCliente2;
    private javax.swing.JLabel lblTelefoneCorretor;
    private javax.swing.JPanel pnlDadosCliente;
    private javax.swing.JPanel pnlDadosCliente1;
    private javax.swing.JPanel pnlDadosCliente2;
    private javax.swing.JPanel pnlDadosCorretor;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtCpfCliente1;
    private javax.swing.JTextField txtCpfCliente2;
    private javax.swing.JTextField txtCpfCorretor;
    private javax.swing.JTextField txtCreciCorretor;
    private javax.swing.JTextField txtDataDeNascimentoCliente;
    private javax.swing.JTextField txtDataDeNascimentoCliente1;
    private javax.swing.JTextField txtDataDeNascimentoCliente2;
    private javax.swing.JTextField txtDataDeNascimentoCorretor;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeCliente1;
    private javax.swing.JTextField txtNomeCliente2;
    private javax.swing.JTextField txtNomeCorretor;
    private javax.swing.JTextField txtOcupacaoCliente;
    private javax.swing.JTextField txtOcupacaoCliente1;
    private javax.swing.JTextField txtOcupacaoCliente2;
    private javax.swing.JTextField txtRgCliente;
    private javax.swing.JTextField txtRgCliente1;
    private javax.swing.JTextField txtRgCliente2;
    private javax.swing.JTextField txtRgCorretor;
    private javax.swing.JTextField txtSalarioCorretor;
    private javax.swing.JTextField txtSenhaCorretor;
    private javax.swing.JTextField txtTelefoneCliente;
    private javax.swing.JTextField txtTelefoneCliente1;
    private javax.swing.JTextField txtTelefoneCliente2;
    private javax.swing.JTextField txtTelefoneCorretor;
    // End of variables declaration//GEN-END:variables
}
