/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Classes.Funcionario;
import dao.FuncionarioDAO;

/**
 * Tela de cadastro de corretor.
 * Essa tela faz as manipulações para salvar um novo corretor.
 * 
 * @author Gabriel Santos Pereira
 */
public class CadastroCorretor extends javax.swing.JFrame {

    static ArrayList<Funcionario> listaFuncionario;
    
    /**
     * Creates new form CadastroCorretor
     */
    public CadastroCorretor() {
        initComponents();
        
        listaFuncionario = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipousuario = new javax.swing.ButtonGroup();
        pnlDadosCorretor = new javax.swing.JPanel();
        lblNomeCorretor = new javax.swing.JLabel();
        lblRgCorretor = new javax.swing.JLabel();
        lblCpfCorretor = new javax.swing.JLabel();
        lblDataDeNascimentoCorretor = new javax.swing.JLabel();
        lblTelefoneCorretor = new javax.swing.JLabel();
        lblSalarioCorretor = new javax.swing.JLabel();
        lblSenhaCorretor = new javax.swing.JLabel();
        txtNomeCorretor = new javax.swing.JTextField();
        txtSalarioCorretor = new javax.swing.JTextField();
        btnSalvarCorretor = new javax.swing.JButton();
        btnLimparCorretor = new javax.swing.JButton();
        btnVoltarTelaPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        radiofuncionario = new javax.swing.JRadioButton();
        radioadm = new javax.swing.JRadioButton();
        txtRgCorretor = new javax.swing.JFormattedTextField();
        txtCpfCorretor = new javax.swing.JFormattedTextField();
        txtDataDeNascimentoCorretor = new javax.swing.JFormattedTextField();
        txtTelefoneCorretor = new javax.swing.JFormattedTextField();
        txtSenhaCorretor = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeCorretor.setText("Nome:");

        lblRgCorretor.setText("RG Corretor:");

        lblCpfCorretor.setText("CPF Corretor:");

        lblDataDeNascimentoCorretor.setText("Data de Nascimento:");

        lblTelefoneCorretor.setText("Telefone:");

        lblSalarioCorretor.setText("Salário:");

        lblSenhaCorretor.setText("Senha:");

        btnSalvarCorretor.setText("Salvar");
        btnSalvarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCorretorActionPerformed(evt);
            }
        });

        btnLimparCorretor.setText("Limpar");
        btnLimparCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCorretorActionPerformed(evt);
            }
        });

        btnVoltarTelaPrincipal.setText("Voltar");
        btnVoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTelaPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        tipousuario.add(radiofuncionario);
        radiofuncionario.setText("Funcionário");
        radiofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofuncionarioActionPerformed(evt);
            }
        });

        tipousuario.add(radioadm);
        radioadm.setText("administrador");

        try {
            txtRgCorretor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRgCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgCorretorActionPerformed(evt);
            }
        });

        try {
            txtCpfCorretor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCorretorActionPerformed(evt);
            }
        });

        try {
            txtDataDeNascimentoCorretor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefoneCorretor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlDadosCorretorLayout = new javax.swing.GroupLayout(pnlDadosCorretor);
        pnlDadosCorretor.setLayout(pnlDadosCorretorLayout);
        pnlDadosCorretorLayout.setHorizontalGroup(
            pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosCorretorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnLimparCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnVoltarTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosCorretorLayout.createSequentialGroup()
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataDeNascimentoCorretor)
                            .addComponent(lblTelefoneCorretor)
                            .addComponent(lblSalarioCorretor))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalarioCorretor)
                            .addComponent(txtTelefoneCorretor)
                            .addComponent(txtDataDeNascimentoCorretor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosCorretorLayout.createSequentialGroup()
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenhaCorretor)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(radiofuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioadm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(txtSenhaCorretor))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosCorretorLayout.createSequentialGroup()
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRgCorretor)
                            .addComponent(lblCpfCorretor)
                            .addComponent(lblNomeCorretor))
                        .addGap(59, 59, 59)
                        .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCorretor)
                            .addComponent(txtRgCorretor)
                            .addComponent(txtCpfCorretor))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlDadosCorretorLayout.setVerticalGroup(
            pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCorretor)
                    .addComponent(txtNomeCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgCorretor)
                    .addComponent(txtRgCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCorretor)
                    .addComponent(txtCpfCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimentoCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataDeNascimentoCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTelefoneCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblSenhaCorretor))
                    .addGroup(pnlDadosCorretorLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtSenhaCorretor, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(radiofuncionario)
                    .addComponent(radioadm))
                .addGap(11, 11, 11)
                .addGroup(pnlDadosCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCorretor)
                    .addComponent(btnVoltarTelaPrincipal)
                    .addComponent(btnSalvarCorretor))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pnlDadosCorretor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(pnlDadosCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaPrincipalActionPerformed
        this.setVisible(false);
        new telaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarTelaPrincipalActionPerformed

    private void btnLimparCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCorretorActionPerformed
    // Limpar os campos
    //txtIdCorretor.setText("");
    txtNomeCorretor.setText("");
    txtRgCorretor.setText("");
    txtCpfCorretor.setText("");
    txtDataDeNascimentoCorretor.setText("");
    txtTelefoneCorretor.setText("");
    txtSalarioCorretor.setText("");
    txtSenhaCorretor.setText("");
    }//GEN-LAST:event_btnLimparCorretorActionPerformed

    private void btnSalvarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCorretorActionPerformed
    // Salvar um novo corretor
    // Faz a validação para saber se preencheu todos os campos
    /*if(txtIdCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    }*/
    if (txtNomeCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtRgCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtCpfCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtDataDeNascimentoCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtTelefoneCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtSalarioCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else if (txtSenhaCorretor.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
    } else {
        //int idCorretor_ = Integer.parseInt(txtIdCliente.getText());
        String nomeCorretor_ = txtNomeCorretor.getText();
        String rgCorretor_ = txtRgCorretor.getText();
        String cpfCorretor_ = txtCpfCorretor.getText();
        String dataNascimentoCorretor_ = txtDataDeNascimentoCorretor.getText();
        String telefoneCorretor_ = txtTelefoneCorretor.getText();
        float salarioCorretor_ = Float.parseFloat(txtSalarioCorretor.getText());
        String senhaCorretor_ = txtSenhaCorretor.getText();
	Boolean adm = false;
	if (radioadm.isSelected()){
	    adm = true;
	} 
	
        Funcionario funcionario = new Funcionario( nomeCorretor_, rgCorretor_, cpfCorretor_, dataNascimentoCorretor_, telefoneCorretor_, salarioCorretor_, senhaCorretor_, adm);
	FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
	if (funcionarioDAO.salvar(funcionario)){ 
	    JOptionPane.showMessageDialog(null, "Cliente cadastrado com Sucesso!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
	    btnLimparCorretorActionPerformed(evt);
	    new telaPrincipal().setVisible(true);
	    this.setVisible(false); 
	}
       
        listaFuncionario.add(funcionario);
        }
    }//GEN-LAST:event_btnSalvarCorretorActionPerformed

    private void radiofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiofuncionarioActionPerformed

    private void txtRgCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgCorretorActionPerformed

    private void txtCpfCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCorretorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparCorretor;
    private javax.swing.JButton btnSalvarCorretor;
    private javax.swing.JButton btnVoltarTelaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpfCorretor;
    private javax.swing.JLabel lblDataDeNascimentoCorretor;
    private javax.swing.JLabel lblNomeCorretor;
    private javax.swing.JLabel lblRgCorretor;
    private javax.swing.JLabel lblSalarioCorretor;
    private javax.swing.JLabel lblSenhaCorretor;
    private javax.swing.JLabel lblTelefoneCorretor;
    private javax.swing.JPanel pnlDadosCorretor;
    private javax.swing.JRadioButton radioadm;
    private javax.swing.JRadioButton radiofuncionario;
    private javax.swing.ButtonGroup tipousuario;
    private javax.swing.JFormattedTextField txtCpfCorretor;
    private javax.swing.JFormattedTextField txtDataDeNascimentoCorretor;
    private javax.swing.JTextField txtNomeCorretor;
    private javax.swing.JFormattedTextField txtRgCorretor;
    private javax.swing.JTextField txtSalarioCorretor;
    private javax.swing.JPasswordField txtSenhaCorretor;
    private javax.swing.JFormattedTextField txtTelefoneCorretor;
    // End of variables declaration//GEN-END:variables
}
