/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Classes.Imovel;
import Classes.Lote;
import Classes.Casa;
import Classes.Apartamento;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author dyesi
 */
public class cadastrarImovel extends javax.swing.JFrame {


    private Imovel imovel = new Casa();
    //private Imovel imovel = new Apartamento();
    //private Imovel imovel = new Lote();


    /**
     * Creates new form cadastrarImovel
     */
    public cadastrarImovel() {
	initComponents();
	
	PainelLote.setVisible(false);
	PainelApartamento.setVisible(false);
	PainelCasa.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoImovel = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioTipoLote = new javax.swing.JRadioButton();
        radioTipoCasa = new javax.swing.JRadioButton();
        radioTipoApartamento = new javax.swing.JRadioButton();
        titulo = new javax.swing.JLabel();
        rua = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        valorCompra = new javax.swing.JLabel();
        dataAquisi = new javax.swing.JLabel();
        PainelLote = new javax.swing.JPanel();
        numeroLote = new javax.swing.JLabel();
        areaLote = new javax.swing.JLabel();
        txtNumeroLote = new javax.swing.JTextField();
        txtAreaLote = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRuaImovel = new javax.swing.JTextField();
        txtBairroImovel = new javax.swing.JTextField();
        txtCepImovel = new javax.swing.JTextField();
        txtCidadeImovel = new javax.swing.JTextField();
        txtValorImovel = new javax.swing.JTextField();
        txtDataAquisicaoImovel = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        PainelApartamento = new javax.swing.JPanel();
        numeroApto = new javax.swing.JLabel();
        numeroAndar = new javax.swing.JLabel();
        quantComodos = new javax.swing.JLabel();
        quantPavimentos = new javax.swing.JLabel();
        valorCondominio = new javax.swing.JLabel();
        idadeImovel = new javax.swing.JLabel();
        txtNumApto = new javax.swing.JTextField();
        txtNumAndarApto = new javax.swing.JTextField();
        txtQuantComodosApto = new javax.swing.JTextField();
        txtQuantPavimentosApto = new javax.swing.JTextField();
        txtValorCondominioApto = new javax.swing.JTextField();
        txtIdadeImovelApto = new javax.swing.JTextField();
        PainelCasa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAreaLoteDaCasa = new javax.swing.JTextField();
        txtAreaConstruidaCasa = new javax.swing.JTextField();
        txtNumeroCasa = new javax.swing.JTextField();
        txtQuantComodosCasa = new javax.swing.JTextField();
        txtQuantPavimentosCasa = new javax.swing.JTextField();
        venda = new javax.swing.JCheckBox();
        aluguel = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdadeCasa = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo:");

        btnGroupTipoImovel.add(radioTipoLote);
        radioTipoLote.setText("Lote");
        radioTipoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoLoteActionPerformed(evt);
            }
        });

        btnGroupTipoImovel.add(radioTipoCasa);
        radioTipoCasa.setText("Casa");
        radioTipoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoCasaActionPerformed(evt);
            }
        });

        btnGroupTipoImovel.add(radioTipoApartamento);
        radioTipoApartamento.setText("Apartamento");
        radioTipoApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoApartamentoActionPerformed(evt);
            }
        });

        titulo.setText("Cadastro de Imóvel");

        rua.setText("Rua:");

        bairro.setText("Bairro:");

        cep.setText("CEP:");

        cidade.setText("Cidade:");

        valorCompra.setText("Valor da compra:");

        dataAquisi.setText("Data da Aquisição:");

        numeroLote.setText("Número do lote:");

        areaLote.setText("Área do lote:");

        txtAreaLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaLoteActionPerformed(evt);
            }
        });

        jLabel11.setText("m²");

        javax.swing.GroupLayout PainelLoteLayout = new javax.swing.GroupLayout(PainelLote);
        PainelLote.setLayout(PainelLoteLayout);
        PainelLoteLayout.setHorizontalGroup(
            PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoteLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaLote)
                    .addComponent(numeroLote))
                .addGap(33, 33, 33)
                .addGroup(PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelLoteLayout.createSequentialGroup()
                        .addComponent(txtAreaLote, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelLoteLayout.setVerticalGroup(
            PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLoteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLote)
                    .addComponent(txtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PainelLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaLote)
                    .addComponent(txtAreaLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        txtBairroImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroImovelActionPerformed(evt);
            }
        });

        txtCidadeImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeImovelActionPerformed(evt);
            }
        });

        txtValorImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorImovelActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        numeroApto.setText("Número do Apartamento:");

        numeroAndar.setText("Número do Andar:");

        quantComodos.setText("Quant de Cômodos:");

        quantPavimentos.setText("Quant de Pavimentos:");

        valorCondominio.setText("Valor do Condomínio:");

        idadeImovel.setText("Idade do Imóvel:");

        txtQuantComodosApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantComodosAptoActionPerformed(evt);
            }
        });

        txtValorCondominioApto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCondominioAptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelApartamentoLayout = new javax.swing.GroupLayout(PainelApartamento);
        PainelApartamento.setLayout(PainelApartamentoLayout);
        PainelApartamentoLayout.setHorizontalGroup(
            PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelApartamentoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroApto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numeroAndar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantComodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantPavimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valorCondominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idadeImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumAndarApto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtNumApto)
                    .addComponent(txtQuantComodosApto)
                    .addComponent(txtQuantPavimentosApto)
                    .addComponent(txtValorCondominioApto)
                    .addComponent(txtIdadeImovelApto))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        PainelApartamentoLayout.setVerticalGroup(
            PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelApartamentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroAndar)
                    .addComponent(txtNumAndarApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroApto)
                    .addComponent(txtNumApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantComodos)
                    .addComponent(txtQuantComodosApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantPavimentos)
                    .addComponent(txtQuantPavimentosApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorCondominio)
                    .addComponent(txtValorCondominioApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PainelApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeImovel)
                    .addComponent(txtIdadeImovelApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel2.setText("Área do Lote:");

        jLabel3.setText("Área Construída:");

        jLabel4.setText("Número da casa:");

        jLabel5.setText("Quant de Cômodos:");

        jLabel6.setText("Quant de Pavimentos:");

        jLabel7.setText("Idade do Imóvel:");

        jLabel8.setText("Disponibilidade:");

        txtAreaConstruidaCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaConstruidaCasaActionPerformed(evt);
            }
        });

        txtQuantComodosCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantComodosCasaActionPerformed(evt);
            }
        });

        venda.setText("venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });

        aluguel.setText("aluguel");

        jLabel9.setText("m²");

        jLabel10.setText("m²");

        javax.swing.GroupLayout PainelCasaLayout = new javax.swing.GroupLayout(PainelCasa);
        PainelCasa.setLayout(PainelCasaLayout);
        PainelCasaLayout.setHorizontalGroup(
            PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCasaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelCasaLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(209, 209, 209))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCasaLayout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(201, 201, 201))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCasaLayout.createSequentialGroup()
                            .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(190, 190, 190)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCasaLayout.createSequentialGroup()
                        .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelCasaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PainelCasaLayout.createSequentialGroup()
                                        .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAreaConstruidaCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(txtAreaLoteDaCasa))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PainelCasaLayout.createSequentialGroup()
                                        .addComponent(venda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37))
                            .addGroup(PainelCasaLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtNumeroCasa)
                                .addGap(64, 64, 64))))))
            .addGroup(PainelCasaLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdadeCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtQuantPavimentosCasa)
                    .addComponent(txtQuantComodosCasa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCasaLayout.setVerticalGroup(
            PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCasaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAreaLoteDaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAreaConstruidaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantComodosCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantPavimentosCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdadeCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(venda)
                    .addComponent(aluguel))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(radioTipoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioTipoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioTipoApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dataAquisi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDataAquisicaoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(valorCompra)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addComponent(txtValorImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cidade))
                                            .addGap(25, 25, 25)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCidadeImovel)
                                                .addComponent(txtCepImovel)
                                                .addComponent(txtBairroImovel)
                                                .addComponent(txtRuaImovel, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))))
                                .addGap(50, 50, 50)
                                .addComponent(PainelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnSalvar)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(85, 85, 85)
                                .addComponent(btnVoltar))
                            .addComponent(PainelLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titulo)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(radioTipoLote)
                    .addComponent(radioTipoCasa)
                    .addComponent(radioTipoApartamento))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rua)
                                .addComponent(txtRuaImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bairro)
                                .addComponent(txtBairroImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cep)
                                .addComponent(txtCepImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cidade)
                                .addComponent(txtCidadeImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(valorCompra)
                                .addComponent(txtValorImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dataAquisi)
                                .addComponent(txtDataAquisicaoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PainelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PainelApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioTipoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoLoteActionPerformed
        // COLOCAR AQUI OQ ACONTECE QUANDO SELECIONO UM LOTE
        PainelLote.setVisible(true);
	PainelApartamento.setVisible(false);
	PainelCasa.setVisible(false);
    }//GEN-LAST:event_radioTipoLoteActionPerformed

    private void radioTipoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoCasaActionPerformed
        // COLOCAR AQUI OQ ACONTECE QUANDO SELECIONO UMA CASA
        PainelLote.setVisible(false);
	PainelApartamento.setVisible(false);
	PainelCasa.setVisible(true);
    }//GEN-LAST:event_radioTipoCasaActionPerformed

    private void radioTipoApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoApartamentoActionPerformed
        // COLOCAR AQUI OQ ACONTECE QUANDO SELECIONO UM APTO
        PainelLote.setVisible(false);
	PainelApartamento.setVisible(true);
	PainelCasa.setVisible(false);
    }//GEN-LAST:event_radioTipoApartamentoActionPerformed

    private void txtAreaLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaLoteActionPerformed

    private void txtBairroImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroImovelActionPerformed

    private void txtCidadeImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeImovelActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Obter os valores dos campos de texto do Imovel
        String rua = txtRuaImovel.getText();
        String bairro = txtBairroImovel.getText();
        String cep = txtCepImovel.getText();
        String cidade = txtCidadeImovel.getText();
        double valorDaCompra = Double.parseDouble(txtValorImovel.getText());
        String dataDaAquisicao = txtDataAquisicaoImovel.getText();
	// TEM QUE FAZER TRATAMENTO DE EXCESSÃO AQUI

	if (radioTipoLote.isSelected()) {
	    // Obter os valores específicos do Lote
	    int numeroLote = Integer.parseInt(txtNumeroLote.getText());
	    double areaDoLote = Double.parseDouble(txtAreaLote.getText());
	    boolean vendido = false;
	    int id = 0;

	    // Criar um objeto Lote com os valores obtidos
	    //Lote lote = new Lote(numeroLote, areaDoLote, vendido, id, rua, bairro, cep, cidade, valorDaCompra, dataDaAquisicao);

	} else if(radioTipoCasa.isSelected()){
	    double tamanhoDoLote = Double.parseDouble(txtAreaLoteDaCasa.getText());
	    double areaConstruida = Double.parseDouble(txtAreaConstruidaCasa.getText());
	    int numeroDaCasa = Integer.parseInt(txtNumeroCasa.getText());
	    int qntDeComodos = Integer.parseInt(txtQuantComodosCasa.getText());
	    int qntDePavimentos = Integer.parseInt(txtQuantPavimentosCasa.getText());
	    int idadeDoImovel = Integer.parseInt(txtIdadeCasa.getText());
	    boolean aluga = aluguel.isSelected();
	    boolean vende = venda.isSelected();
	    boolean disponivel = true;
	    int id = 0;

	    // Cria um objeto Casa com base nos valores dos campos
	    //Casa casa = new Casa(tamanhoDoLote, areaConstruida, numeroDaCasa, qntDeComodos, qntDePavimentos, idadeDoImovel, aluga, vende, disponivel, id, rua, bairro, cep, cidade, valorDaCompra, dataDaAquisicao);

	} else if(radioTipoApartamento.isSelected()){
	    // Obtém os valores dos campos da interface gráfica
	    int numeroDoAndar = Integer.parseInt(txtNumAndarApto.getText());
	    int numeroDoApartamento = Integer.parseInt(txtNumApto.getText());
	    int qntDeComodos = Integer.parseInt(txtQuantComodosApto.getText());
	    int qntDePavimentos = Integer.parseInt(txtQuantPavimentosApto.getText());
	    double valorCondominio = Double.parseDouble(txtValorCondominioApto.getText());
	    int idadeDoImovel = Integer.parseInt(txtIdadeImovelApto.getText());
	    boolean aluga = aluguel.isSelected();
	    boolean vende = venda.isSelected();
	    boolean disponivel = true; // Defina o valor correto aqui
	    int id = 0;

	    // Cria um objeto Apartamento com base nos valores dos campos
	    //Apartamento apartamento = new Apartamento(numeroDoAndar, numeroDoApartamento, qntDeComodos, qntDePavimentos, valorCondominio, idadeDoImovel, aluga, vende, disponivel, id, rua, bairro, cep, cidade, valorDaCompra, dataDaAquisicao);
	}
	//SALVAR NO BD




	
	btnLimparActionPerformed(evt);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
	btnLimparActionPerformed(evt);
	new telaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
	PainelCasa.setVisible(false);
	PainelApartamento.setVisible(false);
	PainelLote.setVisible(false);

	txtBairroImovel.setText("");
	txtCepImovel.setText("");
	txtCidadeImovel.setText("");
	txtDataAquisicaoImovel.setText("");
	txtRuaImovel.setText("");
	txtValorImovel.setText("");

	radioTipoApartamento.setSelected(false);
	radioTipoCasa.setSelected(false);
	radioTipoLote.setSelected(false);

	// painel Lote
	PainelLote.setVisible(false);
	txtAreaLote.setText("");
	txtNumeroLote.setText("");
	
	// painel Casa
	txtAreaLoteDaCasa.setText("");
	txtAreaConstruidaCasa.setText("");
	txtNumeroCasa.setText("");
	txtQuantPavimentosCasa.setText("");
	txtQuantComodosCasa.setText("");
	txtIdadeCasa.setText("");
	venda.setSelected(false);
	aluguel.setSelected(false);

	// painel Apartamento
	txtNumApto.setText("");
	txtNumAndarApto.setText("");
	txtNumeroLote.setText("");
	
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtQuantComodosAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantComodosAptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantComodosAptoActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendaActionPerformed

    private void txtQuantComodosCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantComodosCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantComodosCasaActionPerformed

    private void txtAreaConstruidaCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaConstruidaCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaConstruidaCasaActionPerformed

    private void txtValorCondominioAptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCondominioAptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCondominioAptoActionPerformed

    private void txtValorImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorImovelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(cadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(cadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(cadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(cadastrarImovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new cadastrarImovel().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelApartamento;
    private javax.swing.JPanel PainelCasa;
    private javax.swing.JPanel PainelLote;
    private javax.swing.JCheckBox aluguel;
    private javax.swing.JLabel areaLote;
    private javax.swing.JLabel bairro;
    private javax.swing.ButtonGroup btnGroupTipoImovel;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel dataAquisi;
    private javax.swing.JLabel idadeImovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel numeroAndar;
    private javax.swing.JLabel numeroApto;
    private javax.swing.JLabel numeroLote;
    private javax.swing.JLabel quantComodos;
    private javax.swing.JLabel quantPavimentos;
    private javax.swing.JRadioButton radioTipoApartamento;
    private javax.swing.JRadioButton radioTipoCasa;
    private javax.swing.JRadioButton radioTipoLote;
    private javax.swing.JLabel rua;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtAreaConstruidaCasa;
    private javax.swing.JTextField txtAreaLote;
    private javax.swing.JTextField txtAreaLoteDaCasa;
    private javax.swing.JTextField txtBairroImovel;
    private javax.swing.JTextField txtCepImovel;
    private javax.swing.JTextField txtCidadeImovel;
    private javax.swing.JTextField txtDataAquisicaoImovel;
    private javax.swing.JTextField txtIdadeCasa;
    private javax.swing.JTextField txtIdadeImovelApto;
    private javax.swing.JTextField txtNumAndarApto;
    private javax.swing.JTextField txtNumApto;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtNumeroLote;
    private javax.swing.JTextField txtQuantComodosApto;
    private javax.swing.JTextField txtQuantComodosCasa;
    private javax.swing.JTextField txtQuantPavimentosApto;
    private javax.swing.JTextField txtQuantPavimentosCasa;
    private javax.swing.JTextField txtRuaImovel;
    private javax.swing.JTextField txtValorCondominioApto;
    private javax.swing.JTextField txtValorImovel;
    private javax.swing.JLabel valorCompra;
    private javax.swing.JLabel valorCondominio;
    private javax.swing.JCheckBox venda;
    // End of variables declaration//GEN-END:variables
}
