/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Classes.Cliente;
import dao.ClienteDAO;

/**
 * Tela de cadastro de cliente.
 * Essa tela faz as manipulações para salvar um novo cliente.
 * 
 * @author Gabriel Santos Pereira
 */
public class CadastroCliente extends javax.swing.JFrame {

    static ArrayList<Cliente> listaCliente;
    
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        
        listaCliente = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosCliente = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblRgCliente = new javax.swing.JLabel();
        lblCpfCliente = new javax.swing.JLabel();
        lblDataDeNascimentoCliente = new javax.swing.JLabel();
        lblTelefoneCliente = new javax.swing.JLabel();
        lblOcupacaoCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtRgCliente = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        txtDataDeNascimentoCliente = new javax.swing.JTextField();
        txtTelefoneCliente = new javax.swing.JTextField();
        txtOcupacaoCliente = new javax.swing.JTextField();
        btnSalvarCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        lblNomeCliente.setText("Nome Cliente:");

        lblRgCliente.setText("RG Cliente:");

        lblCpfCliente.setText("CPF Cliente: ");

        lblDataDeNascimentoCliente.setText("Data de Nascimento:");

        lblTelefoneCliente.setText("Telefone:");

        lblOcupacaoCliente.setText("Ocupação do Cliente: ");

        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });

        btnSalvarCliente.setText("Salvar");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setText("Limpar");
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosClienteLayout = new javax.swing.GroupLayout(pnlDadosCliente);
        pnlDadosCliente.setLayout(pnlDadosClienteLayout);
        pnlDadosClienteLayout.setHorizontalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addComponent(lblRgCliente)
                        .addGap(236, 236, 236))
                    .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                            .addComponent(lblCpfCliente)
                            .addGap(18, 18, 18)
                            .addComponent(txtCpfCliente))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                            .addComponent(lblDataDeNascimentoCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtDataDeNascimentoCliente))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                            .addComponent(lblTelefoneCliente)
                            .addGap(35, 35, 35)
                            .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosClienteLayout.createSequentialGroup()
                            .addComponent(lblOcupacaoCliente)
                            .addGap(18, 18, 18)
                            .addComponent(txtOcupacaoCliente))
                        .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                            .addComponent(btnSalvarCliente)
                            .addGap(30, 30, 30)
                            .addComponent(btnLimparCliente)
                            .addGap(26, 26, 26)
                            .addComponent(btnCancelarCliente))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlDadosClienteLayout.setVerticalGroup(
            pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosClienteLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRgCliente)
                    .addComponent(txtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCliente)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimentoCliente)
                    .addComponent(txtDataDeNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneCliente)
                    .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOcupacaoCliente)
                    .addComponent(txtOcupacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCliente)
                    .addComponent(btnCancelarCliente)
                    .addComponent(btnSalvarCliente))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(pnlDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(pnlDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
        // Limpar os campos
        //txtIdCliente.setText("");
        txtNomeCliente.setText("");
        txtRgCliente.setText("");
        txtCpfCliente.setText("");
        txtDataDeNascimentoCliente.setText("");
        txtTelefoneCliente.setText("");
        txtOcupacaoCliente.setText("");
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        // Salvar um novo cliente
        // Faz a validação para saber se preencheu todos os campos
        /*if(txtIdCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        }*/
        if (txtNomeCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        } else if (txtRgCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        } else if (txtCpfCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        } else if (txtDataDeNascimentoCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        } else if (txtTelefoneCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        } else if (txtOcupacaoCliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser inseridos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
        }else {
            //int idCliente_ = Integer.parseInt(txtIdCliente.getText());
            String nomeCliente_ = txtNomeCliente.getText();
            String rgCliente_ = txtRgCliente.getText();
            String cpfCliente_ = txtCpfCliente.getText();
            String dataNascimentoCliente_ = txtDataDeNascimentoCliente.getText();
            String telefoneCliente_ = txtTelefoneCliente.getText();
            String ocupacaoCliente_ = txtOcupacaoCliente.getText();

            Cliente cliente = new Cliente(nomeCliente_, rgCliente_, cpfCliente_, dataNascimentoCliente_, telefoneCliente_, ocupacaoCliente_);
	    ClienteDAO clienteDAO = new ClienteDAO();
	    if (clienteDAO.salvar(cliente)){ 
		JOptionPane.showMessageDialog(null, "Cliente cadastrado com Sucesso!", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
		btnLimparClienteActionPerformed(evt);
		new telaPrincipal().setVisible(true);
		this.setVisible(false);
	    }
            
            listaCliente.add(cliente);
        }
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblDataDeNascimentoCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblOcupacaoCliente;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JPanel pnlDadosCliente;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtDataDeNascimentoCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtOcupacaoCliente;
    private javax.swing.JTextField txtRgCliente;
    private javax.swing.JTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
