/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Classes.Funcionario;
import dao.ImovelDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dyesi
 */
public class telaPrincipal extends javax.swing.JFrame {

    Funcionario funcionarioLogado = new main().funcionarioLogado;

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
        if (funcionarioLogado.isAdm()) {
            btnNovoFuncionario.setVisible(true);
        } else {
            btnNovoFuncionario.setVisible(false);
        }

        ImovelDAO imovelDAO = new ImovelDAO();
        DefaultTableModel tabelaImoveis = (DefaultTableModel) this.tabelaImoveis.getModel();

        imovelDAO.buscarTodos().forEach(imovel -> {
            Object[] dadosImovel = {imovel.getRua(), imovel.getBairro(), imovel.getCep(), imovel.getCidade(), (imovel.isDisponivel() ? "Dísponivel" : "Não disponivel")};
            tabelaImoveis.addRow(dadosImovel);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaImoveis = new javax.swing.JTable();
        btnVenderImovel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImovel = new javax.swing.JMenu();
        jMenuListaImoveis = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuListaClientes = new javax.swing.JMenuItem();
        jMenuNovoCliente = new javax.swing.JMenuItem();
        btnMenuFuncionario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnNovoFuncionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rua", "Bairro", "CEP", "Cidade", "Disponivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaImoveis);

        btnVenderImovel.setText("Vender");
        btnVenderImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderImovelActionPerformed(evt);
            }
        });

        jMenuImovel.setText("Imóveis");

        jMenuListaImoveis.setText("Lista");
        jMenuListaImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaImoveisActionPerformed(evt);
            }
        });
        jMenuImovel.add(jMenuListaImoveis);

        jMenuItem4.setText("Novo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuImovel.add(jMenuItem4);

        jMenuBar1.add(jMenuImovel);

        jMenuCliente.setText("Clientes");

        jMenuListaClientes.setText("Lista");
        jMenuListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaClientesActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuListaClientes);

        jMenuNovoCliente.setText("Novo");
        jMenuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuNovoCliente);

        jMenuBar1.add(jMenuCliente);

        btnMenuFuncionario.setText("Funcionário");
        btnMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuFuncionarioActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Lista");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btnMenuFuncionario.add(jMenuItem1);

        btnNovoFuncionario.setText("Novo");
        btnNovoFuncionario.setMaximumSize(new java.awt.Dimension(1000, 600));
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });
        btnMenuFuncionario.add(btnNovoFuncionario);

        jMenuBar1.add(btnMenuFuncionario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(btnVenderImovel)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenderImovel)
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuListaImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaImoveisActionPerformed
        new Imoveis().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuListaImoveisActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new cadastrarImovel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaClientesActionPerformed
        new Clientes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuListaClientesActionPerformed

    private void jMenuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoClienteActionPerformed
        new CadastroCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuNovoClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Funcionarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        new CadastroCorretor().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void btnVenderImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderImovelActionPerformed
        this.setVisible(false);
        new Transacao().setVisible(true);
    }//GEN-LAST:event_btnVenderImovelActionPerformed

    private void btnMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuFuncionarioActionPerformed

    }//GEN-LAST:event_btnMenuFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnMenuFuncionario;
    private javax.swing.JMenuItem btnNovoFuncionario;
    private javax.swing.JButton btnVenderImovel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuImovel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuListaClientes;
    private javax.swing.JMenuItem jMenuListaImoveis;
    private javax.swing.JMenuItem jMenuNovoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaImoveis;
    // End of variables declaration//GEN-END:variables
}
